version: '3.7'
services:
  nextjs:
    hostname: nextjs
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST: pg-db
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
      POSTGRES_DATABASE: "test_db"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
  db:
    hostname: pg-db
    image: postgres:alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "test_db"]
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
